### ISSUE TITLE
Handle deeper folders

### ISSUE THREAD

**Issue by taqtiqa-mark** [cucumber/action-publish-subrepo#14]
### 🤔 What's the problem you're trying to solve?

```
      - uses: cucumber/action-publish-subrepo@main
        with:
          working-directory: a-folder/a-subfolder/a-subsubfolder
          github-token: ${{ secrets.A_TOKEN }}
          create-subrepo-if-missing: true
```

### ✨ What's your proposed solution?

This action would extract `a-subsubfolder` to the repository `a-repo--a-folder--a-subfolder--a-subsubfolder`. Ack that folder names containing `--` would be out of scope.

### ⛏ Have you considered any alternatives or workarounds?

Current workaround is:

1. Extract `a-folder` to the read-only `a-repo-a-folder`
2. Fork `a-repo-a-folder`
3. Add GH action `action-publish-subrepo` to extract `a-subfolder` to the read-only `a-repo-a-folder-a-subfolder`
4. Fork `a-repo-a-folder-a-subfolder`
5. Add GH action `action-publish-subrepo` to extract `a-subsubfolder` to the read-only `a-repo-a-folder-a-subfolder-a-subsubfolder`

### 📚 Any additional context?

Not that I can think of right now.
